version: 0.2
env:
  secrets-manager:
    # Get SonarCloud credential from AWS Secret Manager: https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=demo-datn-codebuild&region=us-east-1
    LOGIN: demo-datn-codebuild:sonartoken
    # SonarCloud need this env var
    SONAR_TOKEN: demo-datn-codebuild:sonartoken
    HOST: demo-datn-codebuild:HOST
    Organization: demo-datn-codebuild:Organization
    Project: demo-datn-codebuild:Project
phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - apt-cache search apache
      - sudo apt-get update
      - sudo apt-get install apache2 -y
      - sudo service apache2 start 
      - sudo service apache2 status 
      - sudo apt install mysql-server -y
      - sudo service mysql start
  pre_build:
    commands:
      - echo "1. pre build step"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 103448072587.dkr.ecr.us-east-1.amazonaws.com
      - apt-get update
      - apt-get install -y jq
      - echo "Install Sonar scanner binary."
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
  build:
    commands:
      - echo "2. Build step"
      - docker build -f Dockerfile -t mysql .
      - echo "Run SonarCloud scanner"
      - sonar-scanner -Dsonar.organization=ntpthaoo -Dsonar.projectKey=ntpthaoo_Vulnerable-Web-Application -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.php.coverage.reportPaths=coverage.xml
      - sleep 5
      - echo "Get SonarClound scanning result and output it to build log."
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=ntpthaoo_Vulnerable-Web-Application >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then export CODEBUILD_BUILD_SUCCEEDING=0 ;fi
  post_build:
    commands:
      - echo 3. "Post build"
      - echo "3.1 Push img to ECR ---------"
      - docker push 103448072587.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
artifacts:
  files:
    - '***/**'
    
 
